#Generated by Fabric Compiler ( version 2019.1-patch10 <build 44073> ) at Thu Nov  7 15:10:17 2019

project -load "D:/astudy/FPGA_ziguang/CD/demo/13_ddr3_ov5640_hdmi/synthesize/synplify_impl/../synplify_pro.prj"
open_file "D:/astudy/FPGA_ziguang/CD/demo/13_ddr3_ov5640_hdmi/synthesize/synplify_impl/synplify.srm"
