#Generated by Fabric Compiler ( version 2019.1-patch10 <build 44073> ) at Sat Nov 16 16:09:21 2019

project -load "D:/astudy/FPGA_ziguang/CD/demo/13_ddr3_ov5640_hdmi/synthesize/synplify_impl/../synplify_pro.prj"
open_file "D:/astudy/FPGA_ziguang/CD/demo/13_ddr3_ov5640_hdmi/synthesize/synplify_impl/synplify.srs"
